# Generated by Django 5.2.4 on 2025-07-07 18:32
import uuid
from django.db import migrations, models
class Migration(migrations.Migration):
  initial = True
  dependencies = []
  operations = [
    migrations.CreateModel(
      name = 'Lead',
      options = {
        'verbose_name': 'Lead',
        'verbose_name_plural': 'Leads',
        'db_table': 'leads',
      },
      fields = [(
        'id',
        models.UUIDField(
          default = uuid.uuid4,
          editable = False,
          primary_key = True,
          serialize = False
        )
      ), (
        'first_name',
        models.CharField()
      ), (
        'last_name',
        models.CharField()
      ), (
        'email_address',
        models.EmailField(
          unique = True
        )
      ), (
        'phone_number',
        models.CharField()
      ), (
        'message',
        models.TextField(
          blank = True
        )
      ), (
        'owner',
        models.ForeignKey(
          null = True,
          on_delete = models.CASCADE,
          related_name = 'leads',
          to = 'auth.User'
        )
      ), (
        'created_at',
        models.DateTimeField(
          auto_now_add = True
        )
      ), (
        'updated_at',
        models.DateTimeField(
          auto_now = True
        )
      )]
    )
  ]